#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Extract CFG/DFG/CDFG from C files generated by v2c.

By default, scan `.c` files under `benchmark_output/` in the current
directory (skipping `cdfg/` subdirectories).
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from toolchain import ToolNotFoundError, require_tool

# Resolve project paths from the current working directory
# (avoid hard-coded absolute paths).
_BASE_DIR = Path.cwd().resolve()

# Default v2c output scan directory
DEFAULT_C_ROOT_DIR = str((_BASE_DIR / "benchmark_output").resolve())

def _clang_llvm() -> str:
    return require_tool("CLANG_PATH", "clang-16", "clang")


def _opt_llvm() -> str:
    return require_tool("LLVM_OPT_PATH", "opt-16", "opt")

C_KEYWORDS = {
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    "_Alignas",
    "_Alignof",
    "_Atomic",
    "_Bool",
    "_Complex",
    "_Generic",
    "_Imaginary",
    "_Noreturn",
    "_Static_assert",
    "_Thread_local",
}

_LLVM_VALUE_RE = re.compile(r"(%[-a-zA-Z$._0-9]+)")
_LLVM_BLOCK_LABEL_RE = re.compile(r"^\s*([A-Za-z$._][A-Za-z$._0-9-]*):\s*(;.*)?$")
_LLVM_METADATA_DEF_RE = re.compile(r"^!(\d+)\s*=\s*(.+)$")
_LLVM_DBG_ATTACHMENT_RE = re.compile(r"!dbg\s+!(\d+)\b")
_LLVM_QUOTED_FIELD_RE = r'"((?:\\[0-9A-Fa-f]{2}|\\.|[^"\\])*)"'
_C_SCALAR_SUBSCRIPT_RE = re.compile(r"\b([A-Za-z_]\w*)\s*\[\s*(\d+)\s*\]")
_C_FUNC_DEF_RE = re.compile(r"^\s*void\s+[A-Za-z_]\w*\s*\(([^)]*)\)\s*\{", flags=re.M)
_C_SIMPLE_SCALAR_DECL_RE = re.compile(
    r"^\s*(?:unsigned\s+|signed\s+)?(?:short\s+int|long\s+int|long|short|int|char|_Bool)\s+(.+?)\s*;\s*$"
)

_print_lock = threading.Lock()

# Timeout (seconds) for `dot -Tpng` rendering.  Large graphs (>1000 nodes)
# can cause Graphviz to run for hours; 120 s is generous for any graph that
# will actually finish in reasonable time.
DOT_TIMEOUT = 120


def _tprint(*args, **kwargs):
    """Thread-safe print."""
    with _print_lock:
        print(*args, **kwargs)


def _run_dot_png(dot_path: str, png_path: str) -> bool:
    """Run `dot -Tpng` with a timeout.  Returns True on success."""
    try:
        dot = require_tool("DOT_PATH", "dot")
        subprocess.run(
            [dot, "-Tpng", dot_path, "-o", png_path],
            capture_output=True,
            text=True,
            timeout=DOT_TIMEOUT,
        )
        return True
    except subprocess.TimeoutExpired:
        _tprint(f"[WARN] dot timed out ({DOT_TIMEOUT}s) rendering: {dot_path}")
        return False
    except (FileNotFoundError, ToolNotFoundError) as exc:
        _tprint(f"[WARN] dot unavailable; skipped PNG rendering: {exc}")
        return False


def _is_c_identifier(name: str) -> bool:
    return bool(re.match(r"^[A-Za-z_]\w*$", name)) and name not in C_KEYWORDS


def _collect_scalar_identifiers(c_text: str) -> set[str]:
    """
    Collect variable/parameter names that look like scalars in this C file
    (no pointers/arrays), used to fix v2c/AI outputs like `a[3]`.
    Goal: rewrite scalar `x[bit]` into `((x >> bit) & 1)` so clang can emit
    bitcode.
    """
    scalar_names: set[str] = set()

    # 1) Function parameters (v2c output is often single-line `void foo(...) {`)
    for m in _C_FUNC_DEF_RE.finditer(c_text):
        params = (m.group(1) or "").strip()
        if not params or params == "void":
            continue
        for raw in params.split(","):
            p = raw.strip()
            if not p:
                continue
            if "*" in p or "[" in p or "]" in p:
                continue
            tokens = [t for t in re.split(r"\s+", p) if t and t not in ("const", "volatile", "register")]
            if tokens:
                name = tokens[-1].strip()
                if _is_c_identifier(name):
                    scalar_names.add(name)

    # 2) Simple scalar declarations without arrays/pointers
    #    (common v2c form: `unsigned char a;`)
    for line in c_text.splitlines():
        m = _C_SIMPLE_SCALAR_DECL_RE.match(line)
        if not m:
            continue
        decl = m.group(1).strip()
        for part in decl.split(","):
            item = part.strip()
            if not item:
                continue
            # Remove initializer: a = 0
            if "=" in item:
                item = item.split("=", 1)[0].strip()
            if "*" in item or "[" in item or "]" in item:
                continue
            if _is_c_identifier(item):
                scalar_names.add(item)

    return scalar_names


def _rewrite_scalar_bit_subscripts_in_file(path: str) -> bool:
    """
    Rewrite scalar `name[3]` to `((name >> 3) & 1)` to fix clang error:
    `subscripted value is not an array, pointer, or vector`
    """
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            text = f.read()
    except OSError:
        return False

    scalar_names = _collect_scalar_identifiers(text)
    if not scalar_names:
        return False

    def repl(m: re.Match) -> str:
        name = m.group(1)
        bit = m.group(2)
        if name not in scalar_names:
            return m.group(0)
        return f"(({name} >> {bit}) & 1)"

    new_text = _C_SCALAR_SUBSCRIPT_RE.sub(repl, text)
    if new_text == text:
        return False

    with open(path, "w", encoding="utf-8") as f:
        f.write(new_text)
        if not new_text.endswith("\n"):
            f.write("\n")
    return True


def _escape_dot_label(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _safe_filename(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", name)


def _decode_llvm_string(value: str) -> str:
    """Decode the hex escapes used by LLVM metadata strings."""

    def replace_hex(match: re.Match) -> str:
        return chr(int(match.group(1), 16))

    return re.sub(r"\\([0-9A-Fa-f]{2})", replace_hex, value)


def _metadata_int_field(text: str, field: str, default: int = 0) -> int:
    match = re.search(rf"(?:^|[(,]\s*){re.escape(field)}:\s*(\d+)", text)
    return int(match.group(1)) if match else default


def _metadata_ref_field(text: str, field: str) -> str | None:
    match = re.search(rf"(?:^|[(,]\s*){re.escape(field)}:\s*!(\d+)\b", text)
    return match.group(1) if match else None


def _parse_llvm_debug_locations(lines: list[str]) -> dict[str, dict[str, object]]:
    """Resolve ``!dbg !N`` attachments to source file/line/column values."""

    metadata: dict[str, str] = {}
    files: dict[str, str] = {}
    for raw in lines:
        match = _LLVM_METADATA_DEF_RE.match(raw.strip())
        if match:
            metadata[match.group(1)] = match.group(2).strip()

    filename_pattern = re.compile(rf"\bfilename:\s*{_LLVM_QUOTED_FIELD_RE}")
    for metadata_id, text in metadata.items():
        if not text.startswith("!DIFile("):
            continue
        filename_match = filename_pattern.search(text)
        if not filename_match:
            continue
        decoded = _decode_llvm_string(filename_match.group(1))
        files[metadata_id] = os.path.basename(decoded) or decoded

    resolved_files: dict[str, str] = {}

    def resolve_file(metadata_id: str | None, seen: set[str] | None = None) -> str:
        if not metadata_id:
            return ""
        if metadata_id in resolved_files:
            return resolved_files[metadata_id]
        if metadata_id in files:
            resolved_files[metadata_id] = files[metadata_id]
            return files[metadata_id]
        visited = set(seen or set())
        if metadata_id in visited:
            return ""
        visited.add(metadata_id)
        text = metadata.get(metadata_id, "")
        for field in ("file", "scope"):
            resolved = resolve_file(_metadata_ref_field(text, field), visited)
            if resolved:
                resolved_files[metadata_id] = resolved
                return resolved
        return ""

    locations: dict[str, dict[str, object]] = {}
    for metadata_id, text in metadata.items():
        if not text.startswith("!DILocation("):
            continue
        line = _metadata_int_field(text, "line")
        column = _metadata_int_field(text, "column")
        scope_id = _metadata_ref_field(text, "scope")
        location: dict[str, object] = {
            "line": line,
            "column": column,
            "debug_location_id": int(metadata_id),
        }
        source_file = resolve_file(scope_id)
        if source_file:
            location["file"] = source_file
        locations[metadata_id] = location
    return locations


def _debug_location_for_instruction(
    instruction: str,
    locations: dict[str, dict[str, object]],
) -> dict[str, object] | None:
    match = _LLVM_DBG_ATTACHMENT_RE.search(instruction)
    if not match:
        return None
    location = locations.get(match.group(1))
    if not location or int(location.get("line") or 0) <= 0:
        return None
    return dict(location)


def _strip_debug_attachment(instruction: str) -> str:
    return re.sub(r",\s*!dbg\s+!\d+\b", "", instruction).strip()


def _extract_function_name_from_define(line: str) -> str | None:
    m = re.search(r"^\s*define\b.*@(\"([^\"]+)\"|([^(]+))\(", line)
    if not m:
        return None
    return m.group(2) or m.group(3)


def _extract_ssa_args_from_header(header_text: str) -> list[str]:
    m = re.search(r"\((.*)\)", header_text, flags=re.DOTALL)
    if not m:
        return []
    args_text = m.group(1)
    return [a for a in _LLVM_VALUE_RE.findall(args_text) if a]


def _generate_per_function_dfg_from_ll(ll_path: str, dfg_dir: str) -> bool:
    try:
        with open(ll_path, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.read().splitlines()
    except Exception as e:
        _tprint(f"[ERROR] Failed to read LLVM IR: {ll_path}: {e}")
        return False

    os.makedirs(dfg_dir, exist_ok=True)

    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.lstrip().startswith("define "):
            i += 1
            continue

        func_name = _extract_function_name_from_define(line)
        if not func_name:
            i += 1
            continue

        header_lines = [line]
        while i < len(lines) and "{" not in lines[i]:
            i += 1
            header_lines.append(lines[i])
        header_text = "\n".join(header_lines)

        if "{" in lines[i]:
            i += 1

        body_lines: list[str] = []
        while i < len(lines) and lines[i].strip() != "}":
            body_lines.append(lines[i])
            i += 1
        if i < len(lines) and lines[i].strip() == "}":
            i += 1

        nodes: list[tuple[str, str]] = []  # (id, label)
        def_site: dict[str, str] = {}  # %v -> node_id
        edges: set[tuple[str, str]] = set()

        for arg in _extract_ssa_args_from_header(header_text):
            node_id = f"n{len(nodes)}"
            nodes.append((node_id, f"ARG {arg}"))
            def_site[arg] = node_id

        for raw in body_lines:
            s = raw.strip()
            if not s or s.startswith(";"):
                continue
            if s.endswith(":"):
                continue
            s = s.split(" ;", 1)[0].strip()
            if not s:
                continue
            if "@llvm.dbg." in s:
                continue
            s = _strip_debug_attachment(s)

            m_def = re.match(r"^(%[-a-zA-Z$._0-9]+)\s*=\s*(.+)$", s)
            defined = None
            rhs = s
            if m_def:
                defined = m_def.group(1)
                rhs = m_def.group(2)

            node_id = f"n{len(nodes)}"
            nodes.append((node_id, s))

            for u in _LLVM_VALUE_RE.findall(rhs):
                src = def_site.get(u)
                if src:
                    edges.add((src, node_id))

            if defined:
                def_site[defined] = node_id

        dot_name = f"{_safe_filename(func_name)}.dfg.dot"
        dot_path = os.path.join(dfg_dir, dot_name)
        with open(dot_path, "w", encoding="utf-8") as f:
            f.write(f'digraph "DFG_{_escape_dot_label(func_name)}" {{\n')
            f.write('  node [shape=box,fontname="monospace"];\n')
            for nid, label in nodes:
                f.write(f'  {nid} [label="{_escape_dot_label(label)}"];\n')
            for a, b in sorted(edges):
                f.write(f"  {a} -> {b};\n")
            f.write("}\n")

        _run_dot_png(dot_path, os.path.join(dfg_dir, f"{_safe_filename(func_name)}.dfg.png"))

    return True


def _generate_per_function_cdfg_from_ll(ll_path: str, cdfg_dir: str) -> bool:
    """
    Generate per-function CDFG (dot/png):
    CFG (control-flow edges) + Data (SSA def-use) + Mem
    (simple store->load/store dependencies on the same pointer).
    Nodes use short IDs (n0/n1/...), labels store instruction text.
    """
    try:
        with open(ll_path, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.read().splitlines()
    except Exception as e:
        _tprint(f"[ERROR] Failed to read LLVM IR: {ll_path}: {e}")
        return False

    os.makedirs(cdfg_dir, exist_ok=True)
    debug_locations = _parse_llvm_debug_locations(lines)

    def parse_successor_blocks(term: str) -> list[str]:
        succs: list[str] = []
        for m in re.finditer(r"label\s+%([-A-Za-z$._0-9]+)", term):
            succs.append(m.group(1))
        return succs

    def parse_load_ptr(rhs: str) -> str | None:
        m = re.search(r"\bload\b.*?,\s*[^,]*\*\s*(%[-a-zA-Z$._0-9]+)", rhs)
        return m.group(1) if m else None

    def parse_store_ptr(rhs: str) -> tuple[str | None, str | None]:
        m = re.search(
            r"\bstore\b\s+[^,]+\s+(%[-a-zA-Z$._0-9]+),\s*[^,]*\*\s*(%[-a-zA-Z$._0-9]+)",
            rhs,
        )
        if not m:
            return None, None
        return m.group(1), m.group(2)

    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.lstrip().startswith("define "):
            i += 1
            continue

        func_name = _extract_function_name_from_define(line)
        if not func_name:
            i += 1
            continue

        header_lines = [line]
        while i < len(lines) and "{" not in lines[i]:
            i += 1
            header_lines.append(lines[i])
        header_text = "\n".join(header_lines)

        if "{" in lines[i]:
            i += 1

        body_lines: list[str] = []
        while i < len(lines) and lines[i].strip() != "}":
            body_lines.append(lines[i])
            i += 1
        if i < len(lines) and lines[i].strip() == "}":
            i += 1

        blocks: dict[str, list[str]] = {}
        current_bb: str | None = None
        for raw in body_lines:
            m_bb = _LLVM_BLOCK_LABEL_RE.match(raw)
            if m_bb:
                current_bb = m_bb.group(1)
                blocks[current_bb] = []
                continue
            if current_bb is None:
                current_bb = "entry"
                blocks.setdefault(current_bb, [])
            blocks[current_bb].append(raw)

        block_names = set(blocks.keys())

        nodes: list[tuple[str, str, dict[str, object] | None]] = []  # (id, label, source location)
        def_site: dict[str, str] = {}  # %v -> node_id
        inst_by_bb: dict[str, list[str]] = {}  # bb -> [node_id...]
        last_store_by_ptr: dict[str, str] = {}  # %ptr -> store_node_id

        for arg in _extract_ssa_args_from_header(header_text):
            node_id = f"n{len(nodes)}"
            nodes.append((node_id, f"ARG {arg}", None))
            def_site[arg] = node_id

        data_edges: set[tuple[str, str]] = set()
        mem_edges: set[tuple[str, str]] = set()
        ctrl_edges: set[tuple[str, str]] = set()

        def add_inst(
            bb: str,
            inst_text: str,
            defined: str | None,
            rhs: str,
            source_location: dict[str, object] | None,
        ) -> str:
            node_id = f"n{len(nodes)}"
            nodes.append((node_id, inst_text, source_location))
            inst_by_bb.setdefault(bb, []).append(node_id)

            for u in _LLVM_VALUE_RE.findall(rhs):
                if u.startswith("%") and u[1:] in block_names:
                    continue
                src = def_site.get(u)
                if src:
                    data_edges.add((src, node_id))

            if rhs.startswith("load "):
                ptr = parse_load_ptr(rhs)
                if ptr and ptr in last_store_by_ptr:
                    mem_edges.add((last_store_by_ptr[ptr], node_id))
            elif rhs.startswith("store "):
                _, ptr = parse_store_ptr(rhs)
                if ptr and ptr in last_store_by_ptr:
                    mem_edges.add((last_store_by_ptr[ptr], node_id))
                if ptr:
                    last_store_by_ptr[ptr] = node_id

            if defined:
                def_site[defined] = node_id
            return node_id

        for bb, raw_lines in blocks.items():
            for raw in raw_lines:
                s = raw.strip()
                if not s or s.startswith(";"):
                    continue
                if s.endswith(":"):
                    continue
                s = s.split(" ;", 1)[0].strip()
                if not s:
                    continue
                if "@llvm.dbg." in s:
                    continue

                source_location = _debug_location_for_instruction(s, debug_locations)
                s = _strip_debug_attachment(s)

                m_def = re.match(r"^(%[-a-zA-Z$._0-9]+)\s*=\s*(.+)$", s)
                defined = None
                rhs = s
                if m_def:
                    defined = m_def.group(1)
                    rhs = m_def.group(2)
                add_inst(bb, s, defined, rhs, source_location)

        first_inst_of_bb: dict[str, str] = {}
        for bb, insts in inst_by_bb.items():
            if not insts:
                node_id = f"n{len(nodes)}"
                nodes.append((node_id, f"BB {bb}", None))
                inst_by_bb[bb] = [node_id]
                insts = inst_by_bb[bb]
            first_inst_of_bb[bb] = insts[0]
            for a, b in zip(insts, insts[1:]):
                ctrl_edges.add((a, b))

            term_label = nodes[int(insts[-1][1:])][1].strip()
            if "=" in term_label and term_label.startswith("%"):
                term_rhs = term_label.split("=", 1)[1].strip()
            else:
                term_rhs = term_label
            succs = parse_successor_blocks(term_rhs)
            for succ in succs:
                if succ in first_inst_of_bb:
                    ctrl_edges.add((insts[-1], first_inst_of_bb[succ]))

        out_base = _safe_filename(func_name)
        dot_path = os.path.join(cdfg_dir, f"{out_base}.cdfg.dot")
        with open(dot_path, "w", encoding="utf-8") as f:
            f.write(f'digraph "CDFG_{_escape_dot_label(func_name)}" {{\n')
            f.write('  node [shape=box,fontname="monospace"];\n')
            for nid, label, source_location in nodes:
                attributes = [f'label="{_escape_dot_label(label)}"']
                if source_location:
                    source_file = str(source_location.get("file") or "")
                    if source_file:
                        attributes.append(f'source_file="{_escape_dot_label(source_file)}"')
                    attributes.append(f'source_line={int(source_location["line"])}')
                    attributes.append(f'source_column={int(source_location.get("column") or 0)}')
                    attributes.append(
                        f'debug_location_id={int(source_location["debug_location_id"])}'
                    )
                f.write(f"  {nid} [{', '.join(attributes)}];\n")
            for a, b in sorted(ctrl_edges):
                f.write(f'  {a} -> {b} [color="gray50"];\n')
            for a, b in sorted(data_edges):
                f.write(f'  {a} -> {b} [color="black"];\n')
            for a, b in sorted(mem_edges):
                f.write(f'  {a} -> {b} [color="red3"];\n')
            f.write("}\n")

        _run_dot_png(dot_path, os.path.join(cdfg_dir, f"{out_base}.cdfg.png"))

    return True


def _extract_identifier_at_col(code_line: str, col_1based: int) -> str | None:
    if not code_line:
        return None
    idx = max(0, min(col_1based - 1, len(code_line) - 1))

    def is_ident_char(ch: str) -> bool:
        return ch.isalnum() or ch == "_"

    while idx < len(code_line) and not is_ident_char(code_line[idx]):
        idx += 1
    if idx >= len(code_line) or not is_ident_char(code_line[idx]):
        return None

    left = idx
    while left > 0 and is_ident_char(code_line[left - 1]):
        left -= 1
    right = idx
    while right < len(code_line) and is_ident_char(code_line[right]):
        right += 1

    name = code_line[left:right]
    return name if _is_c_identifier(name) else None


def _update_stub_map_from_clang_stderr(stderr_text: str, stub_kinds: dict[str, str]) -> bool:
    lines = stderr_text.splitlines()
    diag_re = re.compile(r"^(.+?):(\d+):(\d+): (warning|error): (.+)$")
    undecl_ident_re = re.compile(r"use of undeclared identifier '([^']+)'")
    undecl_func_re = re.compile(r"call to undeclared function '([^']+)'")

    changed = False
    for i, line in enumerate(lines):
        m = diag_re.match(line.strip())
        if not m:
            continue

        col = int(m.group(3))
        msg = m.group(5)
        code_line = lines[i + 1].strip("\n") if i + 1 < len(lines) else ""
        code_line = code_line.lstrip()

        m_ident = undecl_ident_re.search(msg)
        if m_ident:
            name = m_ident.group(1)
            if _is_c_identifier(name) and stub_kinds.get(name) != "var":
                stub_kinds[name] = "var"
                changed = True
            continue

        m_func = undecl_func_re.search(msg)
        if m_func:
            name = m_func.group(1)
            if _is_c_identifier(name) and stub_kinds.get(name) != "func":
                stub_kinds[name] = "func"
                changed = True
            continue

        if "called object type" in msg and "is not a function" in msg:
            name = _extract_identifier_at_col(code_line, col)
            if name and stub_kinds.get(name) != "func":
                stub_kinds[name] = "func"
                changed = True

    return changed


def _write_stubs_header(path: str, stub_kinds: dict[str, str]) -> None:
    lines: list[str] = ["#pragma once", ""]
    for name in sorted(stub_kinds.keys()):
        kind = stub_kinds[name]
        if kind == "func":
            lines.append(f"extern int {name}();")
        else:
            lines.append(f"extern int {name};")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _compile_c_to_bc_with_stubs(c_path: str, bc_path: str, cwd: str) -> tuple[bool, str]:
    stubs_path = os.path.join(cwd, "stubs.h")
    stub_kinds: dict[str, str] = {}

    base_cmd = [
        _clang_llvm(),
        "-emit-llvm",
        "-c",
        "-O0",
        "-gline-tables-only",
        "-Xclang",
        "-disable-O0-optnone",
        c_path,
        "-o",
        bc_path,
    ]

    for attempt in range(1, 6):
        cmd = list(base_cmd)
        if stub_kinds:
            _write_stubs_header(stubs_path, stub_kinds)
            cmd = cmd[: cmd.index(c_path)] + ["-include", stubs_path] + cmd[cmd.index(c_path) :]

        result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
        if result.stdout:
            _tprint("[clang-16 STDOUT]")
            _tprint(result.stdout)
        if result.stderr:
            _tprint("[clang-16 STDERR]")
            _tprint(result.stderr)
        if result.returncode == 0:
            return True, result.stderr or ""

        changed = _update_stub_map_from_clang_stderr(result.stderr or "", stub_kinds)
        if not changed:
            return False, result.stderr or ""

        _tprint(
            f"[STUB] Compile failed on attempt {attempt}; updated stubs.h "
            f"({len(stub_kinds)} declarations), retrying."
        )

    return False, "Exceeded stub compilation attempts"


def iter_c_files(root_dir: str):
    """
    Recursively traverse root_dir and yield all .c files
    (skips cdfg artifact directories by default).
    """
    for dirpath, dirnames, filenames in os.walk(root_dir):
        dirnames[:] = [d for d in dirnames if d not in (".git", ".idea", "__pycache__") and not d.startswith("cdfg")]
        for filename in filenames:
            if filename.lower().endswith(".c"):
                yield os.path.join(dirpath, filename)


def process_verilog_file_cdfg(c_file: str) -> bool:
    c_file = os.path.abspath(c_file)
    if not os.path.isfile(c_file):
        _tprint(f"[ERROR] C file does not exist: {c_file}")
        return False

    stem, _ = os.path.splitext(os.path.basename(c_file))

    # Output directory: cdfg_<basename> next to the source file.
    src_dir = os.path.dirname(c_file)
    out_dir = os.path.join(src_dir, f"cdfg_{stem}")
    os.makedirs(out_dir, exist_ok=True)

    local_c = os.path.join(out_dir, f"{stem}.c")
    local_cpp = os.path.join(out_dir, f"{stem}.cpp")
    shutil.copy(c_file, local_c)
    shutil.copy(c_file, local_cpp)

    # Fix scalar subscript patterns in some v2c/AI outputs
    # (e.g. `unsigned char a;` but written as `a[3]`).
    patched = _rewrite_scalar_bit_subscripts_in_file(local_c)
    patched |= _rewrite_scalar_bit_subscripts_in_file(local_cpp)
    if patched:
        _tprint(f"[PATCH] Fixed scalar subscript access: {c_file}")

    bc_path = os.path.join(out_dir, f"{stem}.bc")
    _tprint(f"[LLVM] Generating bitcode: {c_file} -> {bc_path}")
    try:
        ok, _ = _compile_c_to_bc_with_stubs(local_c, bc_path, out_dir)
    except ToolNotFoundError as exc:
        _tprint(f"[ERROR] {exc}")
        return False
    if not ok:
        _tprint(f"[ERROR] clang-16 failed to generate bitcode: {c_file}")
        return False

    cfg_dir = os.path.join(out_dir, "cfg")
    os.makedirs(cfg_dir, exist_ok=True)
    _tprint(f"[CFG] Generating CFG(dot): {bc_path} -> {cfg_dir}")
    try:
        opt_llvm = _opt_llvm()
    except ToolNotFoundError as exc:
        _tprint(f"[ERROR] {exc}")
        return False

    cfg_dump = subprocess.run(
        [opt_llvm, "-passes=function(dot-cfg)", "-disable-output", bc_path],
        cwd=cfg_dir,
        capture_output=True,
        text=True,
    )
    if cfg_dump.stdout:
        _tprint("[opt-16 STDOUT]")
        _tprint(cfg_dump.stdout)
    if cfg_dump.stderr:
        _tprint("[opt-16 STDERR]")
        _tprint(cfg_dump.stderr)
    if cfg_dump.returncode != 0:
        _tprint(f"[ERROR] opt-16 failed to generate CFG(dot): {c_file}")
        return False

    cfg_dot_files = [
        f
        for f in os.listdir(cfg_dir)
        if f.startswith(".") and f.endswith(".dot") and os.path.isfile(os.path.join(cfg_dir, f))
    ]
    if not cfg_dot_files:
        _tprint(
            f"[WARN] No CFG dot file found (dot-cfg output is usually hidden, "
            f"e.g. .main.dot). Use 'ls -a {cfg_dir}' to inspect."
        )
    else:
        for dot_name in cfg_dot_files:
            src = os.path.join(cfg_dir, dot_name)
            dst = os.path.join(cfg_dir, dot_name.lstrip("."))
            if os.path.exists(dst):
                os.remove(dst)
            os.rename(src, dst)
            _run_dot_png(dst, os.path.join(cfg_dir, dst.lstrip(".").rsplit(".", 1)[0] + ".png"))

    dfg_dir = os.path.join(out_dir, "dfg")
    os.makedirs(dfg_dir, exist_ok=True)
    for fname in os.listdir(dfg_dir):
        if fname.startswith("ddg.") or fname.endswith(".ddg.dot") or fname.endswith(".ddg.png"):
            try:
                os.remove(os.path.join(dfg_dir, fname))
            except OSError:
                pass

    ll_path = os.path.join(out_dir, f"{stem}.ssa.ll")
    _tprint(f"[DFG] Generating normalized LLVM IR: {bc_path} -> {ll_path}")
    ll_result = subprocess.run(
        [opt_llvm, "-S", "-passes=mem2reg,instnamer", bc_path, "-o", ll_path],
        cwd=out_dir,
        capture_output=True,
        text=True,
    )
    if ll_result.stdout:
        _tprint("[opt-16 STDOUT]")
        _tprint(ll_result.stdout)
    if ll_result.stderr:
        _tprint("[opt-16 STDERR]")
        _tprint(ll_result.stderr)
    if ll_result.returncode != 0:
        _tprint(f"[ERROR] opt-16 failed to generate LLVM IR: {c_file}")
        return False

    _tprint(f"[DFG] Generating DFG(dot) for all functions: {ll_path} -> {dfg_dir}")
    if not _generate_per_function_dfg_from_ll(ll_path, dfg_dir):
        _tprint(f"[ERROR] Failed to generate DFG(dot): {c_file}")
        return False

    cdfg_dir = os.path.join(out_dir, "cdfg_graph")
    os.makedirs(cdfg_dir, exist_ok=True)
    _tprint(f"[CDFG] Generating CDFG(dot) for all functions: {ll_path} -> {cdfg_dir}")
    if not _generate_per_function_cdfg_from_ll(ll_path, cdfg_dir):
        _tprint(f"[ERROR] Failed to generate CDFG(dot): {c_file}")
        return False

    _tprint(f"[DONE] CDFG artifact directory: {out_dir}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract CFG/DFG/CDFG from C files generated by v2c."
    )
    parser.add_argument(
        "target", nargs="?", default=DEFAULT_C_ROOT_DIR,
        help="Single .c file or directory to scan (default: benchmark_output/)",
    )
    parser.add_argument(
        "--workers", "-j", type=int, default=min(os.cpu_count() or 4, 32),
        help="Max parallel workers (default: min(cpu_count, 32)). Use -j 1 for serial.",
    )
    args = parser.parse_args()

    target = os.path.abspath(args.target)
    workers = max(1, args.workers)

    # Single-file mode
    if os.path.isfile(target) and target.lower().endswith(".c"):
        process_verilog_file_cdfg(target)
        return

    if not os.path.isdir(target):
        _tprint(f"Directory does not exist: {target}")
        return

    files = sorted(iter_c_files(target))
    _tprint(f"Start scanning directory: {target}")
    _tprint(f"Files: {len(files)}  Workers: {workers}\n")

    if workers == 1:
        # Serial fallback
        ok = fail = 0
        for i, c_file in enumerate(files, 1):
            if process_verilog_file_cdfg(c_file):
                ok += 1
            else:
                fail += 1
            if i % 10 == 0 or i == len(files):
                _tprint(f"[PROGRESS] {i}/{len(files)}")
    else:
        ok = fail = 0
        done = 0
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futures = {
                pool.submit(process_verilog_file_cdfg, fp): fp
                for fp in files
            }
            for future in as_completed(futures):
                done += 1
                fp = futures[future]
                try:
                    if future.result():
                        ok += 1
                    else:
                        fail += 1
                except Exception as exc:
                    fail += 1
                    _tprint(f"[ERROR] Exception for {fp}: {exc}")
                if done % 10 == 0 or done == len(files):
                    _tprint(f"[PROGRESS] {done}/{len(files)} "
                            f"(ok={ok}, fail={fail})")

    _tprint(f"\nScan complete: {ok + fail} file(s) processed "
            f"(ok={ok}, fail={fail})")


if __name__ == "__main__":
    main()
