##############################################################
# Generated by LLM4SDC Workflow
# Top Module: {top_module}
# Design Name: {design_name}
# RTL Path: {rtl_path}
##############################################################

set top {top_module}
set format {rtl_format}
set design_name {design_name}
set rtl_path {rtl_path}


set_host_options -max_cores {max_cores}
set search_path [list {{search_path}}]
set target_library "{target_library}"
set link_library "{target_library}"

# Read RTL files
analyze -library WORK -format ${format} {rtl_files}
# Elaborate design
elaborate ${top} -library WORK

# Set current design
current_design ${top}

# Link design
link

file mkdir ./syn_output
# Check design
check_design > ./syn_output/check_design.rpt

# ==========================================================================
# Constraints
# ==========================================================================
{sdc_section}
# ==========================================================================

# Compile
{compile_section}

# Generate reports
report_timing > ./syn_output/timing.rpt
report_area > ./syn_output/area.rpt
report_power > ./syn_output/power.rpt
report_resources > ./syn_output/resources.rpt

# Write outputs
write -format verilog -hierarchy -output ./syn_output/${design_name}_syn.sv
write -format ddc -hierarchy -output ./syn_output/${design_name}_syn.ddc
write_sdc -nosplit ./syn_output/${design_name}_syn.sdc

puts "Synthesis completed successfully!"
puts "Outputs written to ./syn_output/"

report_timing -significant_digits 4 -nets -capacitance -transition_time
report_area
report_power

exit
