from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, Iterable, List

from spec_analyze.schema import normalize_interface


_HLS_PRAGMA_RE = re.compile(r"^\s*#pragma\s+HLS\s+(\w+)(.*)$", re.IGNORECASE | re.MULTILINE)
_INTERFACE_MODE_RE = re.compile(r"^\s*(\w+)")
_PORT_DECL_RE = re.compile(
    r"^\s*(?:input|output|inout)\b"
    r"(?:\s+(?:wire|reg|logic|signed|unsigned))*"
    r"(?:\s*\[[^\]]+\])?\s+([^;]+);",
    re.IGNORECASE | re.MULTILINE,
)

_ALLOWED_INTERFACE_MODES = {"ap_none", "ap_ctrl_none"}
_HLS_CONTROL_PORTS = {
    "ap_start",
    "ap_done",
    "ap_idle",
    "ap_ready",
    "ap_continue",
    "ap_ce",
}

_RTL_STYLE_PATTERNS = {
    "generator_banner": re.compile(r"Generated by (?:Vitis HLS|Vivado HLS|Yosys)", re.IGNORECASE),
    "generator_attribute": re.compile(r"CORE_GENERATION_INFO|hls_ip_\d|fsm_encoding", re.IGNORECASE),
    "hls_scheduler": re.compile(
        r"\b(?:ap_CS_fsm|ap_NS_fsm|ap_ST_fsm|ap_phi_mux|ap_ce_reg|ap_block_pp)\b",
        re.IGNORECASE,
    ),
    "hls_temporary_name": re.compile(r"_fu_\d+_p\d+|\b(?:and|or|xor|icmp)_ln\d+\b", re.IGNORECASE),
    "hls_implementation_wrapper": re.compile(r"\bu_impl\b|__impl\b"),
    "simulation_initial_block": re.compile(r"\binitial\s+begin\b", re.IGNORECASE),
}


def _c_container_width(parameter: str) -> int:
    if re.search(r"\b(?:bool|_Bool)\b", parameter):
        return 1
    fixed = re.search(r"\b(?:u?int)(8|16|32|64)_t\b", parameter)
    if fixed:
        return int(fixed.group(1))
    if re.search(r"\bchar\b", parameter):
        return 8
    if re.search(r"\bshort\b", parameter):
        return 16
    if re.search(r"\blong\s+long\b", parameter):
        return 64
    if re.search(r"\blong\b", parameter):
        return 64
    if re.search(r"\bint\b", parameter):
        return 32
    return 0


def _expected_container_width(hardware_width: int) -> int:
    for width in (1, 8, 16, 32, 64):
        if hardware_width <= width:
            return width
    return 0


def audit_c_hls_policy(c_path: str | Path) -> Dict[str, Any]:
    """Reject bus protocols and optimization directives in an HLS baseline."""
    text = Path(c_path).read_text(encoding="utf-8", errors="replace")
    forbidden_interfaces: List[str] = []
    optimization_pragmas: List[str] = []

    for match in _HLS_PRAGMA_RE.finditer(text):
        directive = match.group(1).lower()
        tail = match.group(2).strip()
        pragma = match.group(0).strip()
        if directive != "interface":
            optimization_pragmas.append(pragma)
            continue
        mode_match = _INTERFACE_MODE_RE.match(tail)
        mode = mode_match.group(1).lower() if mode_match else ""
        if mode not in _ALLOWED_INTERFACE_MODES:
            forbidden_interfaces.append(pragma)

    return {
        "success": not forbidden_interfaces and not optimization_pragmas,
        "allowed_interface_modes": sorted(_ALLOWED_INTERFACE_MODES),
        "forbidden_interface_pragmas": forbidden_interfaces,
        "optimization_pragmas": optimization_pragmas,
    }


def audit_c_interface_contract(
    c_path: str | Path,
    interface: Dict[str, Any],
    top_name: str,
) -> Dict[str, Any]:
    """Ensure the C cycle function contains data ports, but no clock/reset arguments."""
    normalized = normalize_interface(interface)
    expected = {
        port["name"]: port
        for port in normalized["ports"]
        if port["role"] not in {"clock", "reset"}
    }
    if not normalized["ports"]:
        return {"success": True, "status": "not_requested"}

    text = Path(c_path).read_text(encoding="utf-8", errors="replace")
    function_match = re.search(
        rf"\bvoid\s+{re.escape(top_name)}\s*\((.*?)\)\s*\{{",
        text,
        re.DOTALL,
    )
    if not function_match:
        return {"success": False, "error": f"top function not found: {top_name}"}

    actual: Dict[str, str] = {}
    actual_widths: Dict[str, int] = {}
    for raw in function_match.group(1).split(","):
        raw = raw.strip()
        if not raw or raw == "void":
            continue
        name_match = re.search(r"([A-Za-z_]\w*)\s*(?:\[[^\]]*\])?\s*$", raw)
        if name_match:
            name = name_match.group(1)
            actual[name] = "output" if "*" in raw else "input"
            actual_widths[name] = _c_container_width(raw)

    clock_reset_names = {
        port["name"]
        for port in normalized["ports"]
        if port["role"] in {"clock", "reset"}
    }
    forbidden_clock_reset_args = sorted(set(actual) & clock_reset_names)
    missing_data_args = sorted(set(expected) - set(actual))
    unexpected_args = sorted(set(actual) - set(expected) - clock_reset_names)
    direction_mismatches = sorted(
        name
        for name in set(expected) & set(actual)
        if expected[name]["direction"] != actual[name]
    )
    container_width_mismatches = sorted(
        name
        for name in set(expected) & set(actual)
        if actual_widths.get(name, 0) != _expected_container_width(int(expected[name]["width"]))
    )
    return {
        "success": not (
            forbidden_clock_reset_args
            or missing_data_args
            or unexpected_args
            or direction_mismatches
            or container_width_mismatches
        ),
        "status": "ok",
        "actual_arguments": actual,
        "actual_container_widths": actual_widths,
        "forbidden_clock_reset_arguments": forbidden_clock_reset_args,
        "missing_data_arguments": missing_data_args,
        "unexpected_arguments": unexpected_args,
        "direction_mismatches": direction_mismatches,
        "container_width_mismatches": container_width_mismatches,
    }


def _declared_port_names(verilog_text: str) -> List[str]:
    names: List[str] = []
    for match in _PORT_DECL_RE.finditer(verilog_text):
        for item in match.group(1).split(","):
            token = item.split("=")[0].strip()
            name_match = re.search(r"([A-Za-z_$][\w$]*)\s*$", token)
            if name_match:
                names.append(name_match.group(1))
    return names


def _top_module_text(verilog_text: str, top_name: str = "") -> tuple[str, str]:
    if top_name:
        match = re.search(
            rf"\bmodule\s+{re.escape(top_name)}\b.*?\bendmodule\b",
            verilog_text,
            re.DOTALL | re.IGNORECASE,
        )
    else:
        match = re.search(r"\bmodule\b.*?\bendmodule\b", verilog_text, re.DOTALL | re.IGNORECASE)
    if not match:
        return "", ""
    module_text = match.group(0)
    name_match = re.search(r"\bmodule\s+([A-Za-z_][A-Za-z0-9_$]*)", module_text)
    return (name_match.group(1) if name_match else ""), module_text


def _numeric_width(msb: str | None, lsb: str | None) -> int:
    if msb is None or lsb is None:
        return 1
    return abs(int(msb) - int(lsb)) + 1


def _parse_top_port_contract(verilog_text: str, top_name: str = "") -> tuple[str, List[Dict[str, Any]]]:
    module_name, module_text = _top_module_text(verilog_text, top_name)
    if not module_text:
        return "", []

    header = re.search(
        rf"\bmodule\s+{re.escape(module_name)}\s*\((.*?)\);",
        module_text,
        re.DOTALL | re.IGNORECASE,
    )
    ports: List[Dict[str, Any]] = []
    if header and re.search(r"\b(?:input|output|inout)\b", header.group(1), re.IGNORECASE):
        for raw in header.group(1).split(","):
            match = re.search(
                r"\b(input|output|inout)\b"
                r"(?:\s+(?:wire|reg|logic|signed|unsigned))*"
                r"(?:\s*\[\s*(-?\d+)\s*:\s*(-?\d+)\s*\])?"
                r"\s+([A-Za-z_][A-Za-z0-9_$]*)\s*$",
                raw.strip(),
                re.IGNORECASE,
            )
            if match:
                ports.append(
                    {
                        "name": match.group(4),
                        "direction": match.group(1).lower(),
                        "width": _numeric_width(match.group(2), match.group(3)),
                    }
                )
        return module_name, ports

    body = module_text[header.end():] if header else module_text
    declaration_re = re.compile(
        r"^\s*(input|output|inout)\b"
        r"(?:\s+(?:wire|reg|logic|signed|unsigned))*"
        r"(?:\s*\[\s*(-?\d+)\s*:\s*(-?\d+)\s*\])?\s+([^;]+);",
        re.IGNORECASE | re.MULTILINE,
    )
    for match in declaration_re.finditer(body):
        for raw_name in match.group(4).split(","):
            name_match = re.search(r"([A-Za-z_][A-Za-z0-9_$]*)\s*$", raw_name.strip())
            if name_match:
                ports.append(
                    {
                        "name": name_match.group(1),
                        "direction": match.group(1).lower(),
                        "width": _numeric_width(match.group(2), match.group(3)),
                    }
                )
    return module_name, ports


def audit_exact_rtl_interface(
    top_verilog: str | Path,
    interface: Dict[str, Any],
    top_name: str,
) -> Dict[str, Any]:
    """Require the public RTL module to match the frozen interface manifest exactly."""
    path = Path(top_verilog)
    text = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
    normalized = normalize_interface(interface)
    expected_ports = normalized["ports"]
    module_name, actual_ports = _parse_top_port_contract(text, top_name)
    expected = {port["name"]: port for port in expected_ports}
    actual = {port["name"]: port for port in actual_ports}

    missing = sorted(set(expected) - set(actual))
    unexpected = sorted(set(actual) - set(expected))
    direction_mismatches = sorted(
        name
        for name in set(expected) & set(actual)
        if expected[name]["direction"] != actual[name]["direction"]
    )
    width_mismatches = sorted(
        name
        for name in set(expected) & set(actual)
        if int(expected[name]["width"]) != int(actual[name]["width"])
    )
    expected_order = [port["name"] for port in expected_ports]
    actual_order = [port["name"] for port in actual_ports]
    order_matches = expected_order == actual_order
    return {
        "success": bool(text) and module_name == top_name and not (
            missing or unexpected or direction_mismatches or width_mismatches
        ) and order_matches,
        "module_name": module_name,
        "expected_top": top_name,
        "expected_ports": expected_ports,
        "actual_ports": actual_ports,
        "missing_ports": missing,
        "unexpected_ports": unexpected,
        "direction_mismatches": direction_mismatches,
        "width_mismatches": width_mismatches,
        "port_order_matches": order_matches,
    }


def audit_rtl_source_style(top_verilog: str | Path, top_name: str = "") -> Dict[str, Any]:
    """Reject recognizable HLS scaffolding from the final human-facing RTL."""
    path = Path(top_verilog)
    text = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
    module_name, top_text = _top_module_text(text, top_name)
    matches: Dict[str, List[str]] = {}
    for label, pattern in _RTL_STYLE_PATTERNS.items():
        found = sorted(set(match.group(0) for match in pattern.finditer(text)))
        if found:
            matches[label] = found[:20]
    return {
        "success": bool(text) and not matches,
        "module_name": module_name,
        "line_count": len(text.splitlines()),
        "module_count": len(re.findall(r"\bmodule\b", text, re.IGNORECASE)),
        "always_block_count": len(re.findall(r"\balways\s*@", top_text, re.IGNORECASE)),
        "assign_count": len(re.findall(r"\bassign\b", top_text, re.IGNORECASE)),
        "forbidden_style_markers": matches,
    }


def audit_rtl_interface(top_verilog: str | Path) -> Dict[str, Any]:
    """Report HLS-specific wrapper ports in the generated top module."""
    path = Path(top_verilog)
    text = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
    _module_name, parsed_ports = _parse_top_port_contract(text)
    ports = [port["name"] for port in parsed_ports]

    axi_ports: List[str] = []
    control_ports: List[str] = []
    handshake_ports: List[str] = []
    native_clock_reset: List[str] = []

    for port in ports:
        lower = port.lower()
        if re.search(r"(?:^|_)(?:m_axi|s_axi|axis)(?:_|$)", lower):
            axi_ports.append(port)
        if lower in _HLS_CONTROL_PORTS:
            control_ports.append(port)
        if lower.endswith(("_ap_vld", "_ap_ack")):
            handshake_ports.append(port)
        if lower in {"ap_clk", "ap_rst", "ap_rst_n"}:
            native_clock_reset.append(port)

    forbidden_ports = sorted(set(axi_ports + control_ports + handshake_ports))
    return {
        "success": bool(text) and not forbidden_ports,
        "ports": ports,
        "axi_ports": sorted(set(axi_ports)),
        "hls_control_ports": sorted(set(control_ports)),
        "hls_handshake_ports": sorted(set(handshake_ports)),
        "hls_clock_reset_ports": sorted(set(native_clock_reset)),
        "forbidden_ports": forbidden_ports,
    }


def relative_verilog_paths(paths: Iterable[Path], root: Path) -> List[str]:
    result: List[str] = []
    for path in paths:
        try:
            result.append(str(path.relative_to(root)))
        except ValueError:
            result.append(str(path))
    return result
