from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Dict, Iterable

from spec_analyze.schema import normalize_interface


_SIMPLE_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_$]*$")
_HLS_OPERATOR_NAME_RE = re.compile(
    r"^(?:and|or|xor|not|icmp|fcmp|select|mux|zext|sext|trunc|shl|shr|ashr|lshr)"
    r"(?:_ln\d+|_\d+|$)",
    re.IGNORECASE,
)
_HLS_SUFFIX_RE = re.compile(r"_fu_\d+_p\d+$", re.IGNORECASE)


def _quoted_path(path: Path) -> str:
    return json.dumps(str(path))


def _run_yosys(yosys: str, script_path: Path, log_path: Path) -> Dict[str, Any]:
    proc = subprocess.run(
        [yosys, "-q", "-s", str(script_path)],
        capture_output=True,
        text=True,
        timeout=300,
    )
    log_path.write_text(proc.stdout + proc.stderr, encoding="utf-8")
    return {
        "success": proc.returncode == 0,
        "returncode": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
        "command": [yosys, "-q", "-s", str(script_path)],
    }


def _unique_name(base: str, reserved: set[str]) -> str:
    candidate = base
    suffix = 2
    while candidate in reserved:
        candidate = f"{base}_{suffix}"
        suffix += 1
    reserved.add(candidate)
    return candidate


def _semantic_name(raw_name: str, reserved: set[str], logic_index: int) -> tuple[str, int]:
    name = re.sub(r"^u_impl\.", "", raw_name)
    name = _HLS_SUFFIX_RE.sub("", name)
    name = re.sub(r"_read_read$", "_read", name)
    name = re.sub(r"[^A-Za-z0-9_$]", "_", name)

    is_generated = (
        not _SIMPLE_IDENTIFIER_RE.match(name)
        or name.startswith("ap_")
        or _HLS_OPERATOR_NAME_RE.match(name) is not None
        or re.search(r"(?:^|_)ln\d+(?:_|$)", name, re.IGNORECASE) is not None
    )
    if is_generated:
        clean = _unique_name(f"logic_{logic_index}", reserved)
        return clean, logic_index + 1
    return _unique_name(name, reserved), logic_index


def _build_rename_commands(
    netnames: Iterable[str],
    *,
    port_names: set[str],
) -> list[str]:
    commands: list[str] = []
    reserved = set(port_names)
    logic_index = 0
    for raw_name in sorted(netnames):
        if raw_name in port_names or raw_name.startswith("$"):
            continue
        clean_name, logic_index = _semantic_name(raw_name, reserved, logic_index)
        if clean_name == raw_name:
            continue
        commands.append(f"rename \\{raw_name} {clean_name}")

    # Private RTLIL names are deterministic compiler temporaries.  Giving them
    # ordinary Verilog identifiers avoids file paths and source line numbers in
    # the emitted RTL.
    commands.append("rename -enumerate -pattern tmp_% w:$*")
    return commands


def _port_declaration(port: Dict[str, Any], *, is_last: bool) -> str:
    width = int(port["width"])
    width_text = "" if width == 1 else f" [{width - 1}:0]"
    comma = "" if is_last else ","
    return f"    {port['direction']} wire{width_text} {port['name']}{comma}"


def _rewrite_module_header(text: str, top_name: str, interface: Dict[str, Any]) -> str:
    normalized = normalize_interface(interface)
    ports = normalized["ports"]
    if not ports:
        raise ValueError("interface manifest has no ports")

    module_re = re.compile(
        rf"\bmodule\s+{re.escape(top_name)}\s*\(.*?\);",
        re.DOTALL,
    )
    if module_re.search(text) is None:
        raise ValueError(f"canonical top module not found: {top_name}")

    header_lines = [f"module {top_name} ("]
    for index, port in enumerate(ports):
        header_lines.append(_port_declaration(port, is_last=index == len(ports) - 1))
    header_lines.append(");")
    text = module_re.sub("\n".join(header_lines), text, count=1)

    # Yosys writes old-style declarations after the module header.  The exact
    # ANSI header above is the public interface, so remove only duplicate
    # one-name declarations for manifest ports.
    for port in ports:
        name = re.escape(port["name"])
        text = re.sub(
            rf"^\s*(?:input|output|inout)\b[^;\n]*\b{name}\s*;\s*\n",
            "",
            text,
            flags=re.MULTILINE,
        )
        text = re.sub(
            rf"^\s*(?:wire|reg)\b(?:\s+signed)?(?:\s*\[[^\]]+\])?\s+{name}\s*;\s*\n",
            "",
            text,
            flags=re.MULTILINE,
        )

    text = re.sub(r"^/\* Generated by Yosys.*?\*/\s*", "", text, count=1)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() + "\n"


def _inline_short_temporaries(text: str, *, max_expression_length: int = 160) -> str:
    """Inline short compiler wires when limited duplication improves readability."""
    for _iteration in range(64):
        lines = text.splitlines()
        declarations: Dict[str, int] = {}
        assignments: Dict[str, tuple[int, str]] = {}
        for index, line in enumerate(lines):
            decl = re.match(
                r"^\s*wire(?:\s+signed)?(?:\s*\[[^\]]+\])?\s+((?:tmp|logic)_\d+)\s*;\s*$",
                line,
            )
            if decl:
                declarations[decl.group(1)] = index
            assign = re.match(r"^\s*assign\s+((?:tmp|logic)_\d+)\s*=\s*(.*);\s*$", line)
            if assign:
                assignments[assign.group(1)] = (index, assign.group(2).strip())

        changed = False
        for name in sorted(set(declarations) & set(assignments)):
            assign_index, expression = assignments[name]
            if len(expression) > max_expression_length:
                continue
            uses = 0
            use_index = -1
            pattern = re.compile(rf"\b{re.escape(name)}\b")
            for index, line in enumerate(lines):
                if index in {declarations[name], assign_index}:
                    continue
                count = len(pattern.findall(line))
                if count:
                    uses += count
                    use_index = index
            if uses < 1 or uses > 2 or len(expression) * uses > max_expression_length:
                continue
            for index, line in enumerate(lines):
                if index in {declarations[name], assign_index}:
                    continue
                lines[index] = pattern.sub(f"({expression})", line)
            lines[declarations[name]] = ""
            lines[assign_index] = ""
            text = "\n".join(lines)
            changed = True
            break
        if not changed:
            break
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() + "\n"


def _format_simple_clocked_blocks(text: str) -> str:
    pattern = re.compile(
        r"^\s*always\s*@\(([^\n]+)\)\s*\n"
        r"\s*if\s*\(([^\n]+)\)\s+([A-Za-z_][A-Za-z0-9_$]*)\s*<=\s*([^;]+);\s*\n"
        r"\s*else\s+\3\s*<=\s*([^;]+);\s*$",
        re.MULTILINE,
    )

    def replace(match: re.Match[str]) -> str:
        sensitivity = re.sub(r"\s*,\s*", " or ", match.group(1).strip())
        condition = match.group(2).strip()
        register = match.group(3)
        reset_value = match.group(4).strip()
        next_value = match.group(5).strip()
        return (
            f"  always @({sensitivity}) begin\n"
            f"    if ({condition})\n"
            f"      {register} <= {reset_value};\n"
            f"    else\n"
            f"      {register} <= {next_value};\n"
            "  end"
        )

    return pattern.sub(replace, text)


def canonicalize_hls_rtl(
    input_path: str | Path,
    output_path: str | Path,
    *,
    top_name: str,
    interface: Dict[str, Any],
) -> Dict[str, Any]:
    """Flatten and normalize HLS RTL into a single hardware-native module.

    This is deterministic RTL canonicalization, not an HLS optimization pass.
    It removes redundant scheduling structure after HLS and never inserts HLS
    directives such as PIPELINE, UNROLL, DATAFLOW, or resource binding.
    """
    input_path = Path(input_path).resolve()
    output_path = Path(output_path).resolve()
    normalized = normalize_interface(interface)
    yosys = shutil.which("yosys")

    if not input_path.is_file():
        return {"success": False, "error": f"input RTL not found: {input_path}"}
    if not yosys:
        return {"success": False, "error": "yosys is required for clean RTL canonicalization"}
    if not _SIMPLE_IDENTIFIER_RE.match(top_name):
        return {"success": False, "error": f"invalid top module name: {top_name}"}
    if not normalized["ports"]:
        return {"success": False, "error": "interface manifest has no ports"}

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="module5_hls_canonical_") as tmp_dir_str:
        tmp_dir = Path(tmp_dir_str)
        design_json = tmp_dir / "design.json"
        inspect_script = tmp_dir / "inspect.ys"
        inspect_log = tmp_dir / "inspect.log"
        common_passes = [
            f"read_verilog -sv {_quoted_path(input_path)}",
            f"hierarchy -check -top {top_name}",
            "proc",
            "flatten",
            # Ignore simulation-only power-on values under the explicit reset
            # contract before proving and applying structural cleanup passes.
            "setattr -unset init w:*",
            "fsm",
            "opt -full",
            "clean -purge",
        ]

        transform_proof_script = tmp_dir / "transform_proof.ys"
        transform_proof_log = tmp_dir / "transform_proof.log"
        transform_proof_script.write_text(
            "\n".join(
                [
                    f"read_verilog -sv {_quoted_path(input_path)}",
                    f"hierarchy -check -top {top_name}",
                    "proc",
                    "flatten",
                    "setattr -unset init w:*",
                    "equiv_opt -assert -async2sync fsm",
                    "equiv_opt -assert -async2sync opt -full",
                    "equiv_opt -assert -async2sync clean -purge",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        transform_proof_result = _run_yosys(
            yosys,
            transform_proof_script,
            transform_proof_log,
        )
        if not transform_proof_result["success"]:
            return {
                "success": False,
                "error": "HLS RTL cleanup pass equivalence checking failed",
                "transform_equivalence": transform_proof_result,
            }
        inspect_script.write_text(
            "\n".join([*common_passes, f"write_json {_quoted_path(design_json)}", ""]),
            encoding="utf-8",
        )
        inspect_result = _run_yosys(yosys, inspect_script, inspect_log)
        if not inspect_result["success"] or not design_json.is_file():
            return {
                "success": False,
                "error": "Yosys failed while inspecting HLS RTL",
                "inspect": inspect_result,
            }

        payload = json.loads(design_json.read_text(encoding="utf-8"))
        module = (payload.get("modules", {}) or {}).get(top_name, {})
        netnames = list((module.get("netnames", {}) or {}).keys())
        port_names = {port["name"] for port in normalized["ports"]}
        rename_commands = _build_rename_commands(netnames, port_names=port_names)

        preformatted_path = tmp_dir / "preformatted.v"
        emit_script = tmp_dir / "emit.ys"
        emit_log = tmp_dir / "emit.log"
        emit_script.write_text(
            "\n".join(
                [
                    *common_passes,
                    f"cd {top_name}",
                    *rename_commands,
                    f"write_verilog -noattr -nodec {_quoted_path(preformatted_path)}",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        emit_result = _run_yosys(yosys, emit_script, emit_log)
        if not emit_result["success"] or not preformatted_path.is_file():
            return {
                "success": False,
                "error": "Yosys failed while emitting canonical RTL",
                "inspect": inspect_result,
                "emit": emit_result,
            }

        try:
            text = preformatted_path.read_text(encoding="utf-8", errors="replace")
            text = _rewrite_module_header(text, top_name, normalized)
            text = _inline_short_temporaries(text)
            text = re.sub(r"\b1'h([01x])\b", r"1'b\1", text, flags=re.IGNORECASE)
            text = _format_simple_clocked_blocks(text)
            output_path.write_text(text, encoding="utf-8")
        except Exception as exc:
            return {
                "success": False,
                "error": f"failed to format canonical RTL: {exc}",
                "inspect": inspect_result,
                "emit": emit_result,
            }

        proof_script = tmp_dir / "proof.ys"
        proof_log = tmp_dir / "proof.log"
        proof_script.write_text(
            "\n".join(
                [
                    f"read_verilog -sv {_quoted_path(preformatted_path)}",
                    f"hierarchy -check -top {top_name}",
                    "proc",
                    "async2sync",
                    "opt_clean",
                    "rename -top gold",
                    "design -stash gold_design",
                    "design -reset-vlog",
                    f"read_verilog -sv {_quoted_path(output_path)}",
                    f"hierarchy -check -top {top_name}",
                    "proc",
                    "async2sync",
                    "opt_clean",
                    "rename -top gate",
                    "design -stash gate_design",
                    "design -copy-from gold_design -as gold gold",
                    "design -copy-from gate_design -as gate gate",
                    "equiv_make gold gate equiv",
                    "hierarchy -check -top equiv",
                    "equiv_simple",
                    "equiv_induct -seq 8",
                    "equiv_status -assert",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        proof_result = _run_yosys(yosys, proof_script, proof_log)
        if not proof_result["success"]:
            return {
                "success": False,
                "error": "canonical RTL failed deterministic equivalence checking",
                "inspect": inspect_result,
                "emit": emit_result,
                "equivalence": proof_result,
                "transform_equivalence": transform_proof_result,
            }

    return {
        "success": True,
        "status": "ok",
        "input_path": str(input_path),
        "output_path": str(output_path),
        "top": top_name,
        "tool": yosys,
        "passes": ["proc", "flatten", "fsm", "opt -full", "clean -purge"],
        "removed_simulation_initial_values": True,
        "reset_assumption": "The manifest reset is asserted before functional operation.",
        "renamed_public_internal_nets": len(rename_commands) - 1,
        "equivalence": proof_result,
        "transform_equivalence": transform_proof_result,
        "equivalence_scope": (
            "cleanup_passes_and_preformatted_canonical_rtl_vs_final_rtl"
        ),
        "interface": normalized,
    }
